### ISSUE TITLE
System.Exception: RBrokerEngine: taskTokenListener callback not found for DeployRBroker.PooledTask, unexpected error.

### ISSUE THREAD

**Issue by alena-zhuk** [deployr/dotnet-rbroker-framework#5]
When I'm doing many concurrent pooled task execution using single RBroker, sometimes RBrokerWorkerManager method fails with an exception:

`Exception: Exception thrown: 'System.Exception' in DeployRBroker8.0.5.dll ("RBrokerEngine: brokerEngineExecutor.run ex=System.Exception: RBrokerEngine:  processing task DeployRBroker.PooledTask, ex=System.Exception: RBrokerEngine: taskTokenListener callback not found for DeployRBroker.PooledTask, unexpected error.
   at DeployRBroker.RBrokerEngine.RBrokerWorkerManager()
   at DeployRBroker.RBrokerEngine.RBrokerWorkerManager()"). Exception thrown: 'System.Exception' in DeployRBroker8.0.5.dll ("RBrokerEngine: brokerEngineExecutor.run ex=System.Exception: RBrokerEngine:  processing task DeployRBroker.PooledTask, ex=System.Exception: RBrokerEngine: taskTokenListener callback not found for DeployRBroker.PooledTask, unexpected error.
   at DeployRBroker.RBrokerEngine.RBrokerWorkerManager()
   at DeployRBroker.RBrokerEngine.RBrokerWorkerManager()")`

Once the RBrokerWorkerManager method throws the exception, RBroker basically stops task processing and new tasks keep queuing.
I tested on series of 100 concurrent calls with parallelTaskLimit = 6.

It happens sometimes in case when a task has been sent to submit and was successfully added into pending tasks queue (`m_pendingHighPriorityQueue`/`m_pendingLowPriorityQueue`). At the same time the task could be picked up in different thread by  `RBrokerWorkerManager`, although the task was not completely submitted yet. In some cases `RBrokerWorkerManager` tries to take the task token listener from `m_taskTokenListenerMap`before it was created and added there in submit method. So it cause that `m_taskTokenListenerMap.TryRemove` returns null since such key was not found. Then  `RBrokerWorkerManager` throws an exception, which I described above. 
I haven't found any logic that would restart `RBrokerWorkerManager` to continue task processing after failure. 

Assuming that I see two point to improve:
1. \- [ ] RBrokerWorkerManager should restart after fail
2. \- [ ] A task and its result token object should be added to the m_taskTokenListenerMap dictionary before the task would be queued to process.

**Comment by dec100** [comment]
Sorry for the long delay, I missed this thread.  Can you provide some steps to help replicate the error?
